name       : pwgen
version    : 2.07
release    : 1
source     :
    - http://sourceforge.net/projects/pwgen/files/pwgen/2.07/pwgen-2.07.tar.gz : eb74593f58296c21c71cd07933e070492e9222b79cedf81d1a02ce09c0e11556
license    : GPL-2.0
summary    : Password generator for creating easily memorable passwords
description: |
    Password generator for creating easily memorable passwords
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
