name       : pwgen
version    : '2.08'
release    : 3
source     :
    - https://downloads.sourceforge.net/project/pwgen/pwgen/2.08/pwgen-2.08.tar.gz : dab03dd30ad5a58e578c5581241a6e87e184a18eb2c3b2e0fffa8a9cf105c97b
homepage   : https://sourceforge.net/projects/pwgen/
license    : GPL-2.0-only
component  : security
summary    : Password generator for creating easily memorable passwords
description: |
    The pwgen program generates passwords which are designed to be easily memorized by humans, while being as secure as possible.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
