name       : pwgen
version    : '2.08'
release    : 2
source     :
    - https://nchc.dl.sourceforge.net/project/pwgen/pwgen/2.08/pwgen-2.08.tar.gz : dab03dd30ad5a58e578c5581241a6e87e184a18eb2c3b2e0fffa8a9cf105c97b
license    : GPL-2.0
component  : security
summary    : Password generator for creating easily memorable passwords
description: |
    Password generator for creating easily memorable passwords
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
